$(document).ready(function() {
  // LIBRARIES CODE
  LibVars = {};
  // PROJECT CODE
  var _that = this;
  // Block#: epW!*wH3W}T(Q4QL$T@Y
  function on_Button_click(e) {
    try {
      // Block#: LP~7f$KF9xH-*w}Wmbtl
      console.log('dsfdsfsdf');
      if(_that.debugService && _that.debugService.active) {
        _that.debugService.traces.push('dsfdsfsdf');
        _that.debugService.printLog();
      }
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Button"]').on('click', on_Button_click);
  $('[obj-name="MainScreen"]').show();
});
// Generated by snapp
// 405829-293131-391215-17284
